import { PrismaClient } from '@prisma/client';

// This is a standard pattern to prevent creating multiple Prisma Client instances
// during development with hot-reloading.
const globalForPrisma = global as unknown as { prisma: PrismaClient };

const prismaClient = globalForPrisma.prisma || new PrismaClient({
    log: ['query', 'info', 'warn', 'error'],
});

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prismaClient;
}

// Explicitly export the prisma client instance.
// This is what the 'SyntaxError' was complaining about.
export const prisma = prismaClient;

// Also, re-export all the types generated by Prisma.
// This allows other packages to get full end-to-end type safety like:
// import type { User, Course } from '@synergylearn/db';
export * from '@prisma/client';
